# Generated by Django 3.0.5 on 2020-04-30 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200430_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='_id',
            new_name='post_id',
        ),
    ]
