# Generated by Django 3.0.5 on 2020-05-03 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200501_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='details',
            new_name='author',
        ),
    ]
